# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name cbind_Rcpp
#' @title cbind_rcpp
#' Take a sequence of vector, matrix or data-frame arguments and
#' combine by columns or rows, respectively.
#'
#' @param a,b A NumericMatrix that takes a numerical vector value as a parameter, and the elements in it are double.
#' @examples
#' a <- matrix(rnorm(1e7), 1e3)
#' b <- matrix(runif(1e7), 1e3)
#' identical(mmult1(a, b), mmult1(a, b))
#' @export
mmult1 <- function(a, b) {
    .Call('_Taller1v2_mmult1', PACKAGE = 'Taller1v2', a, b)
}

#' @name mmatrix_rcpp
#' @title mmatrix_rcpp
#' Multiplies two matrices, if they are conformable
#'
#' @param m1,m2 A NumericMatrix that takes a numerical vector value as a parameter, and the elements in it are double.
#' @examples
#' set.seed(42)
#' A <- matrix(c(1:6),ncol=2)
#' B <- matrix(c(0:7),nrow=2)
#' mmult(A,B)
#' @export
mmult <- function(m1, m2) {
    .Call('_Taller1v2_mmult', PACKAGE = 'Taller1v2', m1, m2)
}

#' @name rbind_Rcpp
#' @title rbind_rcpp
#' Used to bind or combine the multiple group of rows together.
#'
#' @param a,b A NumericMatrix that takes a numerical vector value as a parameter, and the elements in it are double.
#' @examples
#' set.seed(42)
#' a <- matrix(rnorm(1e7), 1e3)
#' b <- matrix(runif(1e7), 1e3)
#' identical(mmult1(a, b), mmult1(a, b))
#' @export
mmult1 <- function(a, b) {
    .Call('_Taller1v2_mmult1', PACKAGE = 'Taller1v2', a, b)
}

#' @name wich_max_rcpp
#' @title wich_max_rcpp
#' Find the maximum values of a data frame or array.
#'
#' @param A NumericMatrix that takes a numerical vector value as a parameter, and the elements in it are double.
#' @examples
#' set.seed(42)
#' a <- matrix(rnorm(1e7), 1e3)
#' b <- matrix(runif(1e7), 1e3)
#'
#' @export
Wichmax_rcpp <- function(A) {
    .Call('_Taller1v2_Wichmax_rcpp', PACKAGE = 'Taller1v2', A)
}

#' @name wich_min_rcpp
#' @title wich_min_rcpp
#' Find the minimum values of a data frame or array.
#'
#' @param A NumericMatrix that takes a numerical vector value as a parameter, and the elements in it are double.
#' @examples
#' set.seed(42)
#' a <- matrix(rnorm(1e7), 1e3)
#' b <- matrix(runif(1e7), 1e3)
#'
#' @export
Wichmax_rcpp <- function(A) {
    .Call('_Taller1v2_Wichmax_rcpp', PACKAGE = 'Taller1v2', A)
}

